# Generated by Django 5.0.7 on 2024-07-13 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricingrule',
            name='product_id',
        ),
        migrations.AddField(
            model_name='pricingrule',
            name='collection_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pricingrule',
            name='product_ids',
            field=models.TextField(blank=True, null=True),
        ),
    ]
