# Generated by Django 5.0.7 on 2024-07-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_pricingrule_product_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricingrule',
            name='collection_id',
        ),
        migrations.AddField(
            model_name='pricingrule',
            name='collection_ids',
            field=models.TextField(blank=True, null=True),
        ),
    ]
